### ISSUE TITLE
Mac OS support 

### ISSUE THREAD

**Issue by alexey-gruzdev** [intel/openfl#213]
Add support to Mac users for OpenFL.

**Comment by CasellaJr** [comment]
Hello. After running `fx` i have this error: 
`from contextlib import asynccontextmanager

ImportError: cannot import name 'asynccontextmanager'`

**Comment by alexey-gruzdev** [comment]
@CasellaJr hey! thanks for interest in OpenFL. Could you please post details around you MacOS, Python, and how you install OpenFL in it?

**Comment by CasellaJr** [comment]
@alexey-gruzdev Hello, thank you.
I have a MacBook Pro (Retina, 13-inch, Early 2015), CPU 2,7 GHz Intel Core i5 dual-core, and MacOS BigSur
Conda: 4.9.2
I created a virtual env as written in the guide: https://openfl.readthedocs.io/en/latest/install.initial.html
1. conda create -n my_env pip python=3.6
2. conda activate my_env
3. git clone https://github.com/intel/openfl.git
4. cd openfl/
5. pip install .
6. fx
The problem is here, when I write fx: `from contextlib import asynccontextmanager

ImportError: cannot import name 'asynccontextmanager'`

**Comment by alexey-gruzdev** [comment]
@CasellaJr okay, thanks for clarification. Could I kindly ask you to try python3.7 or 3.8. Because, from initial search looks like it's [python3.6 issue](https://stackoverflow.com/questions/65268193/unable-to-import-asynccontextmanager-from-contextlib) with context lib

**Comment by CasellaJr** [comment]
@alexey-gruzdev Okay, it seems working with Python 3.7
I tried also with Python 3.9 but it does not work

**Comment by alexey-gruzdev** [comment]
@CasellaJr either 3.7 or 3.8 should work:) then, I will take a note about that. We don't have a official MacOS support yet, but it would be good to know about your findings

**Comment by MasterSkepticista** [comment]
Closing due to inactivity.
