### ISSUE TITLE
Issue observed in experimental aggregator based workflow

### ISSUE THREAD

**Issue by ishant162** [intel/openfl#989]
**Describe the bug**
Running Experimental aggregator based workflow workspace 101_torch_cnn_mnist leads to an unexpected **ImportError** Exception.

**To Reproduce**
1. Create workspace using `fx workspace create --prefix my_workspace --template 101_torch_cnn_mnist`
2. Complete workspace creation using `fx` commands by following steps described in the last cell of this [tutorial](https://github.com/securefederatedai/openfl/blob/develop/openfl-tutorials/experimental/Workflow_Interface_1001_Workspace_Creation_from_JupyterNotebook.ipynb)
3. Run aggregator using `fx aggregator start`
4. See error **ImportError: cannot import name 'Aggregator' from partially initialized module 'openfl.experimental.component.aggregator'**

**Expected behavior**
Workspace should run successfully without any error.

**Desktop (please complete the following information):**
 - OS: Ubuntu (WSL)
 - OS Version: 22.04.3 LTS
 - Python: 3.8.19

**Error logs**
[Import_error_logs.txt](https://github.com/user-attachments/files/15774239/Import_error_logs.txt)

**Additional context**
The issue appears to have arisen due to the code changes introduced in PR #980 
@MasterSkepticista Can you please look into this?

**Comment by MasterSkepticista** [comment]
Hi @ishant162, this is due to a circular import error which needs fixes as and when they are encountered. This is done as a wider refactor effort on using absolute instead of relative imports.

Refer to the discussion in #980 on refactor of imports.

Can you raise a PR with the following change? (ensure it passes your test)
```python
# openfl/experimental/component/aggregator/__init__.py
# Change
from openfl.experimental.component.aggregator import Aggregator

# To
from openfl.experimental.component.aggregator.aggregator import Aggregator
```

**Comment by ishant162** [comment]
@MasterSkepticista, Thank you for the information. I will proceed with raising a PR to incorporate the suggested changes.

**Comment by ishant162** [comment]
Fixed in #974
