### PR TITLE
Fixed ImportError issue in Experimental aggregator based workflow

### LINKED ISSUE #989: Issue observed in experimental aggregator based workflow
**Describe the bug**
Running Experimental aggregator based workflow workspace 101_torch_cnn_mnist leads to an unexpected **ImportError** Exception.

**To Reproduce**
1. Create workspace using `fx workspace create --prefix my_workspace --template 101_torch_cnn_mnist`
2. Complete workspace creation using `fx` commands by following steps described in the last cell of this [tutorial](https://github.com/securefederatedai/openfl/blob/develop/openfl-tutorials/experimental/Workflow_Interface_1001_Workspace_Creation_from_JupyterNotebook.ipynb)
3. Run aggregator using `fx aggregator start`
4. See error **ImportError: cannot import name 'Aggregator' from partially initialized module 'openfl.experimental.component.aggregator'**

**Expected behavior**
Workspace should run successfully without any error.

**Desktop (please complete the following information):**
 - OS: Ubuntu (WSL)
 - OS Version: 22.04.3 LTS
 - Python: 3.8.19

**Error logs**
[Import_error_logs.txt](https://github.com/user-attachments/files/15774239/Import_error_logs.txt)

**Additional context**
The issue appears to have arisen due to the code changes introduced in PR #980 
@MasterSkepticista Can you please look into this?

### PR DESCRIPTION
**Pull request by ishant162**
Updated openfl/experimental/component/aggregator/__init__.py

Ran the following tutorials and test cases:

- Experimental workspace 101_torch_cnn_mnist, 301_torch_cnn_mnist_watermarking
- Experimental workspace testcase:
         - testcase_datastore_cli
         - testcase_private_attributes
         - testcase_reference
         - testcase_internalloop

No Issues observed

This PR fixes #989

### CODE REVIEW

**Review by psfoley — APPROVED** [review]

**Review by MasterSkepticista — APPROVED** [review]

**Comment by ishant162** [comment]
Closing this PR as the changes have already been merged in #974
